ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('store.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/store/urls.py
from django.urls import path
from .views import *

from django.conf import settings
from django.conf.urls.static import static
app_name = 'store'
urlpatterns = [
    path('', store, name='store'),
    path('cart/add/<int:id>/', cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         item_increment, name='item_increment'),
    path('cart/cart_clear/', cart_clear, name='cart_clear'),
    path('cart/cart_detail/', cart_detail, name='cart_detail'),
]

ecommerce/store/models.py
from django.db import models

# Create your models here.

class product(models.Model):
    name = models.CharField(max_length=30)
    Reference = models.CharField(default='145',max_length=30)
    image = models.FileField(upload_to='store/static/store/img')
    price = models.FloatField()
#    def save(self):
#        self.file_name = self.Rep.split('//')[:-1]
#        super().save(self)
    def __str__(self):
        return self.name

ecommerce/store/views.py
from django.shortcuts import render,redirect
from .models import *
from cart.cart import Cart
# Create your views here.
lst = [['Fromage','1','fromage.jpg',3.0],['Pain','2','pain.jpg',1.0],['Tomate','3','tomate.jpg',1.0]]
def store(request):

    queryset = product.objects.filter(name='fromage')

    for i in lst:
        prod = product()
        prod.name = i[0]
        prod.Reference = i[1]
        prod.image = i[2]
        prod.price = i[3]
        prod.save()

    qs = product.objects.all()
    key_set = set()
    delete_ids_list = []
    for object in qs:
        object_key = object.name  # photo_id here
        if object_key in key_set:
            delete_ids_list.append(object.id)
        else:
            key_set.add(object_key)
    product.objects.filter(id__in=delete_ids_list).delete()
    query_results = product.objects.all()
    print(query_results)
    context = {'query_results': query_results}
    return render(request, 'store.html',context=context)





def cart_add(request, id):
    cart = Cart(request)
    Product = product.objects.get(id=id)
    cart.add(product=Product)
    return redirect("/")



def item_clear(request, id):
    cart = Cart(request)
    Product = product.objects.get(id=id)
    cart.remove(Product)
    return redirect("/cart/cart_detail/")



def item_increment(request, id):
    cart = Cart(request)
    Product = product.objects.get(id=id)
    cart.add(product=Product)
    return redirect("/")






def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("/")



def cart_detail(request):
    return render(request, 'cart.html')

ecommerce/store/templates/cart.html
{% extends "store.html" %}
{% block title %}cart{% endblock title %}
{% load static %}
{% load cart_tag %}
{% block content %}

	</div>
<link href="{% static 'store/css/style_cart.css' %}" rel="stylesheet">
<div class="container padding-bottom-3x mb-1">
    <!-- Shopping Cart-->
    <div class="table-responsive shopping-cart">
        <table class="w3-table">
            <thead>
                <tr>
                    <th>Produit</th>
                    <th class="text-center">Quantité</th>

                    <th class="text-center">Totale</th>

                    <th class="text-center">Discount</th>
                </tr>
            </thead>
            <tbody>
			{% for key,value in request.session.cart.items %}
                <tr>
                    <td>
                        <div class="product-item">
                            <a class="product-thumb" href="#{{value.Reference}}"><img src="/store/static/store/img{{value.image}}" alt="Product"></a>
                            <div class="product-info">
                                <h4 class="product-title"><a href="#">{{value.name}}</a></h4><span><em>Size:</em> 10.5</span><span><em>Color:</em> Dark Blue</span>
                            </div>
                        </div>
                    </td>
                    <td class="text-center">
                        <div class="count-input">
                            <select class="form-control">
                                <option>{{value.quantity}}</option>
								</option>
                            </select>
                        </div>
                    </td>
                    <td class="text-center text-lg text-medium">{{ value.price|multiply:value.quantity }}€</td>
                    <td class="text-center text-lg text-medium">{{ value|isdiscount }}€</td>
                    <td class="text-center"><a class="remove-from-cart" href="#" data-toggle="tooltip" title="" data-original-title="Remove item"><i class="fa fa-trash"></i></a></td>
                </tr>
			{% endfor %}
            </tbody>
        </table>
    </div>
    <div class="shopping-cart-footer">


        <div class="column text-lg">Totale : {{ request.session.cart.items|totale}}€ <span class="text-medium"></span></div>
    </div>

</div>
{% endblock content %}

ecommerce/store/templates/main.html
{% load static %}
{% block content %}

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>grocery shopping </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'store/img/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'store/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">Shopping</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                        </button>
                    </form>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Grocery Shopping</h1>

                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <div class="col mb-5">
                        <div class="card h-100">
                                                        <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">2 produits achetés = 1 offert</div>
                            <!-- Product image-->
                            <img class="card-img-top" src="{% static 'store/img/pain.jpg' %}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Pain</h5>
                                    <!-- Product price-->
                                    1 €
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">2 produits achetés = 1 offert</div>
                            <!-- Product image-->
                            <img class="card-img-top" src="{% static 'store/img/fromage.jpg' %}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Fromage</h5>
                                    <!-- Product price-->
                                    <span class="text-muted text-decoration-line-through">3 €</span>
                                    1.5 €
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">2 produits achetés = 1 offert</div>
                            <!-- Product image-->
                            <img class="card-img-top" src="{% static 'store/img/tomate.jpg' %}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Tomate</h5>
                                    <!-- Product price-->
                                    1 €
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'store/js/scripts.css' %}"></script>
    </body>
</html>
{% endblock content %}

ecommerce/store/templates/store.html
{% load static %}
{% block content %}
{% load cart_tag %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Magasin en Ligne </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'store/img/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'store/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">Shopping</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>

                    </ul>
                    <form class="d-flex">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" target="_blank" href="{% url 'store:cart_detail' %}">Cart ({{request.session.cart.items|totale_qt}}) </a></div>
                        </div>
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" target="_blank" href="{% url 'store:cart_clear' %}">Clear Cart</a></div>
                        </div>
                    </form>

                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Magasin</h1>

                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                                        {% csrf_token%}
                    {% for item in query_results %}
                    <div class="col mb-5">
                        <div class="card h-100">
                                                        <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">2 produits achetés = 1 offert</div>
                            <!-- Product image-->
                            <a href="#{{item.Reference}}" data-toggle="modal">
                            <img class="card-img-top" src= "store/static/store/img{{item.image.url}}" /></a>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{item.name}}</h5>
                                    <!-- Product price-->
                                    {{item.price}} €
                                </div>

                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'store:cart_add' item.id %}">Ajouter au panier</a></div>
                            </div>
                        </div>
                    </div>
                     {% endfor %}


                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'store/js/scripts.css' %}"></script>
    </body>
</html>
{% endblock content %}